basePath: /
definitions:
  github_com_hameedhub_pismo_internal_model.Account:
    properties:
      account_id:
        type: integer
      balance:
        type: number
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      document_number:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  github_com_hameedhub_pismo_internal_model.Transaction:
    properties:
      account_id:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      event_date:
        type: string
      id:
        type: integer
      operation_type_id:
        type: integer
      transaction_id:
        type: integer
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a pismo server.
  title: Swagger Pismo API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Create a new account with the input payload
      parameters:
      - description: Create Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/github_com_hameedhub_pismo_internal_model.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_hameedhub_pismo_internal_model.Account'
      summary: Create a new account
      tags:
      - accounts
  /accounts/{id}:
    get:
      description: Get details of an account corresponding to the input ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hameedhub_pismo_internal_model.Account'
      summary: Get an account by ID
      tags:
      - accounts
  /transactions:
    post:
      consumes:
      - application/json
      description: Create a new transaction with the input payload
      parameters:
      - description: Create Transaction
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/github_com_hameedhub_pismo_internal_model.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_hameedhub_pismo_internal_model.Transaction'
      summary: Create a new transaction
      tags:
      - transactions
swagger: "2.0"
